### ISSUE TITLE
Generic Agent GUI

### ISSUE THREAD

**Issue by dennybresch** [dennybresch/OTRS-QuickDelete#3]
Hi @SynPrime,

let's move on.
Now we need a GenericAgent, which we can create via CodeInstall->PackageSetup->ObjectAdd
Here you can see what the way should look like.
I'll just leave you alone for now and wonder how far you'll get.
:) 
Please, Don't hesitate if you need help.

- [x] CodeInstall in SOPM
```xml
<CodeReinstall Type="post"><![CDATA[
        $Kernel::OM->Get('var::packagesetup::OTRSQuickDelete')->CodeReinstall();
    ]]></CodeReinstall>
<CodeInstall Type="post"><![CDATA[
        $Kernel::OM->Get('var::packagesetup::OTRSQuickDelete')->CodeInstall();
    ]]></CodeInstall>
<CodeUninstall Type="pre"><![CDATA[
        $Kernel::OM->Get('var::packagesetup::OTRSQuickDelete')->CodeUninstall();
    ]]></CodeUninstall>
<CodeUpgrade Type="post"><![CDATA[
        $Kernel::OM->Get('var::packagesetup::OTRSQuickDelete')->CodeUpgrade();
    ]]></CodeUpgrade>
```

---

- [x] var::packagesetup::OTRSQuickDelete
Example: https://github.com/OTRS/ITSMConfigurationManagement/blob/rel-6_0/var/packagesetup/ITSMConfigurationManagement.pm

---

- [x] GenericAgent
   - [x] check if exists 
   - [x] create job if not

```perl
    $GenericAgentObject->JobAdd(
        Name => 'JobName',
        Data => {
            Queue => 'SomeQueue',
            ...
            Valid => 1,
        },
        UserID => 123,
    );

```

**Comment by SynPrime** [comment]
Hey @dennybresch ,

I've pushed the current version of the code.

**Comment by dennybresch** [comment]
👍 NICE man.

I commited some changes, but all in all = good job! 🚀 

https://github.com/dennybresch/OTRS-QuickDelete/commit/a679df49fe1a8cc93c135d857379e923e5392aa4
